# Generated by Django 4.2.3 on 2023-08-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('asosiy', '0003_alter_mahsulot_son'),
        ('statistika', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatistikaViews',
            new_name='Statistika',
        ),
    ]
