# Generated by Django 4.2.3 on 2023-08-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0003_statistika_olchov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='nasiya',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistika',
            name='summa',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='statistika',
            name='tolangan_summa',
            field=models.IntegerField(),
        ),
    ]
