# Generated by Django 4.2.3 on 2023-08-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0005_alter_statistika_olchov'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistika',
            name='miqdor',
            field=models.IntegerField(),
        ),
    ]
