# Generated by Django 4.2.3 on 2023-08-03 03:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_mahsulot_omborxona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='son',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
