# Generated by Django 4.2.3 on 2023-08-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0003_alter_mahsulot_son'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mijoz',
            name='qarz',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
