# Generated by Django 4.2.3 on 2023-08-08 04:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0004_alter_mijoz_qarz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='narx',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='son',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
